import { Inter } from 'next/font/google'
import './globals.css'

// import Course from './components/Course'
// import Blog from './components/blogg/Blog'

// import LandingPage from './components/LandingPage'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <LandingPage/> */}
      {/* <Course/>   */}
      {/* <Blog/> */}
      {children}
      </body>
    </html>
  )
}
